### ISSUE TITLE
gem install command not working

### ISSUE THREAD

**Issue by pmsteil** [radekg/knife-aws-extensions#3]
When I run

gem install knife-aws-extensions

my server tells me:

ERROR:  Could not find a valid gem 'knife-aws-extensions' (>= 0) in any repository

Any ideas?

**Comment by galindro** [comment]
Same issue with me

**Comment by radekg** [comment]
Updated the readme. This stuff is not distributed via rubygems.
To install:

```
gem install specific_install
gem specific_install https://github.com/radekg/knife-aws-extensions.git
```

**Comment by galindro** [comment]
Not works too

``` bash
gem specific_install https://github.com/radekg/knife-aws-extensions.git
git installing from https://github.com/radekg/knife-aws-extensions.git
Cloning into '/tmp/d20141119-3625-180d4ga'...
remote: Counting objects: 42, done.
remote: Total 42 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (42/42), done.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `build' for Gem::Package:Module
```

**Comment by radekg** [comment]
This works:

```
git clone https://github.com/radekg/knife-aws-extensions.git
cd knife-aws-extensions/
gem build knife-aws-extensions.gemspec
gem install $(ls | grep *.gem)
```

I'd suggest bundler though.

**Comment by galindro** [comment]
Another problem:

``` bash
# gem list |grep ec
knife-ec2 (0.8.0)
specific_install (0.2.11)
# gem install --local $(ls | grep *.gem)
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: knife-aws-extensions requires knife-ec2 (~> 0.6.2)
```

Isn't possible to compile it ignoring that requirement or upgrade it to support knife ec2 version > 0.6.x ?

**Comment by radekg** [comment]
I corrected my comment right after adding it. The correct command is:

```
gem install $(ls | grep *.gem)
```

not `--local`. `--local` will not attempt downloading dependencies.

**Comment by galindro** [comment]
Not worked too

``` bash
# gem install $(ls | grep *.gem)
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fog requires excon (~> 0.25.0), ruby-hmac (>= 0)
```

**Comment by galindro** [comment]
Even installing dependencies excon and ruby-hmac via gem install, the issue continues.

``` bash
# gem install excon ruby-hmac
Fetching: excon-0.41.0.gem (100%)
Successfully installed excon-0.41.0
Fetching: ruby-hmac-0.4.0.gem (100%)
Successfully installed ruby-hmac-0.4.0
2 gems installed
Installing ri documentation for excon-0.41.0...
Installing ri documentation for ruby-hmac-0.4.0...
Installing RDoc documentation for excon-0.41.0...
Installing RDoc documentation for ruby-hmac-0.4.0...

# gem install $(ls | grep *.gem)
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fog requires excon (~> 0.25.0)
```

**Comment by radekg** [comment]
I've updated the dependencies to the more recent ones. If it still doesn't work, I'll happily accept a pull request!

**Comment by galindro** [comment]
Using "gem specific_install" doesn't works:

``` bash
# gem specific_install https://github.com/radekg/knife-aws-extensions.git
git installing from https://github.com/radekg/knife-aws-extensions.git
Cloning into '/tmp/d20141121-3064-1t4d0ji'...
remote: Counting objects: 45, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 45 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (45/45), done.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `build' for Gem::Package:Module
```

This package doesn't works with knife-ec2 version > 0.8.0 (I'm using v 0.10.0). So, I've updated knife-aws-extensions.gemspec to permit knife-ec2 version >= 0.8.0 and proceeded with bundler install. The installation worked fine, but it seems the code has a bug:

``` bash
# knife aws
/var/lib/gems/1.9.1/gems/chef-11.16.4/lib/chef/knife/core/subcommand_loader.rb:34:in `load': /var/lib/gems/1.9.1/gems/knife-aws-extensions-0.1.0/lib/chef/knife/ec2_server_start.rb:152: syntax error, unexpected $end, expecting keyword_end (SyntaxError)
    from /var/lib/gems/1.9.1/gems/chef-11.16.4/lib/chef/knife/core/subcommand_loader.rb:34:in `block in load_commands'
    from /var/lib/gems/1.9.1/gems/chef-11.16.4/lib/chef/knife/core/subcommand_loader.rb:34:in `each'
    from /var/lib/gems/1.9.1/gems/chef-11.16.4/lib/chef/knife/core/subcommand_loader.rb:34:in `load_commands'
    from /var/lib/gems/1.9.1/gems/chef-11.16.4/lib/chef/knife.rb:120:in `load_commands'
    from /var/lib/gems/1.9.1/gems/chef-11.16.4/lib/chef/knife.rb:168:in `run'
    from /var/lib/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/knife.rb:139:in `run'
    from /var/lib/gems/1.9.1/gems/chef-11.16.4/bin/knife:25:in `<top (required)>'
    from /usr/local/bin/knife:19:in `load'
    from /usr/local/bin/knife:19:in `<main>'
```
